### ISSUE TITLE
(SA-1) Super Mario RPG (and others) - Resetting console goes to black screen

### ISSUE THREAD

**Issue by tcprescott** [RedGuyyyy/sd2snes#8] opened 2018-08-03 23:38 UTC
Firmware version - 1.8.0 sa1 v2
sd2snes rev. H
Hardware - North American NTSC Super Nintendo, unsure if 1chip or 3chip
Games affected - SMRPG and VLDC9 SMW hack

Issue - When I quickly slide the reset switch on the SNES console, instead of the game restarting the console just goes to black and does nothing else.  Powering off and powering back on the console then sends you to the sd2snes menu as intended.  It happened randomly three times while playing SMRPG and the VLDC9 SMW hack, but in the last few attempts I haven't been able to reproduce the issue.  I've never noticed the issue with stock firmware (1.8.0 and earlier versions).

I initially thought it was only after I had saved, but I saved and reset the console and the game reset correctly.  I'll do some more testing to see if I can find a pattern.

I've attempted to replicate the issue on my SuperNT without success.  I'll update this thread if it does happen on that console.

Let me know if you need more details.

**Comment by James-F2** [comment] 2018-08-04 08:38
>  the game isn't properly restarting.

What exactly does it mean?
What do you see on screen?

**Comment by tcprescott** [comment] 2018-08-04 23:26
Hi James, I updated the post with more details of what I specifically noticed.  It could very well be something with my console, I haven't been able to get it to replicate on my SuperNT.

**Comment by Rahzadan** [comment] 2018-08-06 13:50
SD2SNES rev. H - SA-1 v03 firmware.
I have confirmed this behavior on my SNS-CPU-RGB-01 3chip console. I am also unable to reproduce this issue on my Super NT (Firwmare 4.5). 

This does NOT occur on my REAL SMRPG cart on my SNS-CPU-RGB-01 3chip console.

**Comment by James-F2** [comment] 2018-08-08 04:44
It may be related to the J.League 96 black screen I'm experiencing on my 3Chip NTSC.

**Comment by James-F2** [comment] 2018-08-08 14:34
Confirmed.

Can't go back to menu.
Only way it to power off the console.

**Comment by James-F2** [comment] 2018-08-08 18:57
Fixed with latest commit.

**Comment by Rahzadan** [comment] 2018-08-08 19:35
Isn't happening anymore for me either on v04 + recent commit to fix this problem. I hit reset on my 3chip 25+ times and it reset properly each time.

**Comment by Rahzadan** [comment] 2018-08-09 12:02
Based on discussions on other channels (Classic Gaming Discord Server, etc) it would appear that there are variations on different 3chip consoles which seems to make this issue more apparent, or more frequent on "older" (slower) 3chip consoles. The age of capacitors, revision of particular components on the different SNES PCB revisions seems to also seem to affect how frequently this issue occurs, This issue probably stems from the fact that the SD2SNES draws more power than a standard SNES cartridge.

It's also been confirmed that this issue does not seem to occur on a 1chip or on a Super NT, likely because these consoles can handle the extra power draw of the SD2SNES more consistently.

Due to this, it may not be possible to fix this issue 100%, however the issue has been improved significantly with the v04 release. It could still happen on a console with weak capacitors.

**Comment by James-F2** [comment] 2018-08-10 05:11
This issue has nothing to do with power.
RedGuy already fixed it and it should work on all consoles now.

**Comment by RedGuyyyy** [comment] 2018-08-13 16:27
Fixed in v05.

**Closed by RedGuyyyy** 2018-08-13 16:27 UTC
