### ISSUE TITLE
(SA-1) Super Robot Taisen Gaiden - Random lockups on 1-Chip

### ISSUE THREAD

**Issue by sonikkufan** [RedGuyyyy/sd2snes#7] opened 2018-08-03 15:17 UTC
Sometimes when I boost arms/units for heralds in the game the game locks up and when I reset I notice that my save file is gone.

**Comment by RedGuyyyy** [comment] 2018-08-07 01:59
Does this still happen with v03?  I've tried it several times with v03 plus some unrelated changes and can't get it to lockup.  I've only tried after the first battle with ~6000 credits, though.  If you're using a translation/romhack make sure you have the latest version and it works ok in an emulator.

**Comment by sonikkufan** [comment] 2018-08-08 05:34
It seems to be fixed in v03.

**Comment by RedGuyyyy** [comment] 2018-08-08 14:34
Assumed to be fixed in v03.  I was not able to reproduce it in that version.

**Closed by RedGuyyyy** 2018-08-08 14:34 UTC
