### ISSUE TITLE
(SA-1) Super Mario RPG freezes

### ISSUE THREAD

**Issue by lunderhage** [RedGuyyyy/sd2snes#10] opened 2018-08-04 13:47 UTC
Hi,
I have experienced freezing on Super Mario RPG twice now in a short moment of time:
Yo'ster Isle: After winning the race against Boshi.
Mole Mine: During enemy fight.

Music continues to play, but game is completely frozen.
I'm playing on a PAL SNES running the sa1_v02 version.

(Great thank you for your time!)

**Comment by James-F2** [comment] 2018-08-04 14:43
Does your PAL snes have Super-CIC installed or are you playing NTSC rom on a pure 50Hz PAL console?

**Comment by lunderhage** [comment] 2018-08-04 18:43
Non-modified PAL console using the NTSC rom. (There is no PAL version of SMRPG as far as I know)

**Comment by SmokeMonsterPacks** [comment] 2018-08-04 18:58
@lunderhage There is no official PAL version, but you can apply this hack to patch it to 50mhz and essentially make your own PAL SMRPG: https://www.romhacking.net/hacks/2779/

**Comment by lunderhage** [comment] 2018-08-05 10:05
Doesn't SD2SNES do the 50hz patch automagically when running NTSC games? Anyway, I'll try this out and see if still freezes.

**Comment by Rahzadan** [comment] 2018-08-06 13:55
Tried to reproduce this issue in both of these areas on my SD2SNES rev H - SNES model SNS-CPU-RGB-01 3chip NTSC USA console multiple times and I did not experience these issues.

I imagine this may have to do with the fact that you are running an NTSC ROM on your PAL SNES.

**Comment by lunderhage** [comment] 2018-08-08 08:50
After some hours of testing with a rom patched with the above patch and firmware v03, I haven't had any issues so far.

**Comment by Rahzadan** [comment] 2018-08-08 10:32
Since the PAL-->NTSC patch is working on you, I think we can chalk up your issues to an incompatibility between PAL and NTSC, or some kind of change between v02 and v03 of the SA-1 firmware which fixed it for you, since no one else has reported these freezes, and you said it works OK after patching your ROM. It's quite likely that the real cartridge has similar issues due to the CIC chip. Either way, for the purposes of this bug report, that doesn't really matter.

I recommend closing this issue.

**Comment by RedGuyyyy** [comment] 2018-08-08 14:33
Assumed to be fixed in v03.

**Closed by RedGuyyyy** 2018-08-08 14:33 UTC

**Comment by lunderhage** [comment] 2018-08-08 20:10
Now it froze again on the word puzzle on the sunken ship.

**Comment by RedGuyyyy** [comment] 2018-08-13 16:28
Try v05.  I rewrote some stuff that had known bugs.
