### ISSUE TITLE
(SA-1) J.League 96 Dream Stadium, will not boot consistently on a 3chip.

### ISSUE THREAD

**Issue by James-F2** [RedGuyyyy/sd2snes#9] opened 2018-08-04 05:56 UTC
Firmware SA-1 Beta v02 + August 4th commits.

Black screen at boot on a 3chip (GPM-01 and RGB-01).

Seems to load consistently on a 3chip SHVC-CPU-01 (first revision of snes).
Loads fine and consistently on a 1Chip and SuperNT.

**Comment by vitaflo** [comment] 2018-08-04 16:44
Boots properly on my SNS-CPU-GPM-02.

**Comment by Rahzadan** [comment] 2018-08-05 23:27
Boots fine each time (tried 5 hard resets and 5 boots to be sure) on my SNS-CPU-RGB-01

Using SA-1 Beta v03 firmware.

**Comment by James-F2** [comment] 2018-08-08 19:15
Fixed with latest commit.

**Comment by Rahzadan** [comment] 2018-08-09 11:59
Based on discussions on other channels (Classic Gaming Discord Server, etc) it would appear that there are variations on different 3chip consoles which seems to make this issue more apparent, or more frequent on "older" (slower) 3chip consoles. The age of capacitors, revision of particular components on the different SNES PCB revisions seems to also seem to affect how frequently this issue occurs, This issue probably stems from the fact that the SD2SNES draws more power than a standard SNES cartridge.

It's also been confirmed that this issue does not occur on a 1chip or on a Super NT, likely because these consoles can handle the extra power draw of the SD2SNES more consistently.

Due to this, it may not be possible to fix this issue 100%.

**Comment by James-F2** [comment] 2018-08-09 13:47
I have a 78S05 and a 470uF installed in this snes, so it is not power ralated.
Great Hierophant's RGB-01 has this issue too.
These snes consoles may be on the edge of the tolerance of "something".

**Comment by James-F2** [comment] 2018-08-19 04:05
This seems to be fixed now on my slow 3chip GPM-01 since the **"Added simpler and lower latency snes read of mmio/iram"** commit.

**Comment by RedGuyyyy** [comment] 2018-08-19 14:12
Appears to be fixed in v06.

**Closed by RedGuyyyy** 2018-08-19 14:12 UTC
